### ISSUE TITLE
Data Cleaning

### ISSUE THREAD

**Issue by simplymathematics** [simplymathematics/forecasting-project#2]
- [x] Imputation
- [ ] Normalization?
- [ ] Stationarity?
- [x] BoxCox?

**Comment by ann2014** [comment]
I don't think that we will need Normalization and Stationarity. Data are transformed using YeoJohnson method. I am open to suggestions. I think that Stationarity is most likely for time series, and Normalization is for Neural Networks. I could be wrong, in that case, I will add them later.
